export const breweries = [
{ name:"Red Oak Brewing", street:"120 Maple St", city:"Portland", state:"Oregon", postal_code:"97201", brewery_type:"micro", phone:"5031110001", website_url:"http://redoakbrew.com" },
{ name:"River Bend Brewery", street:"88 River Rd", city:"Bend", state:"Oregon", postal_code:"97701", brewery_type:"micro", phone:"5411110002", website_url:"http://riverbendbrew.com" },
{ name:"Iron Hill Brewing", street:"210 Industrial Ave", city:"Denver", state:"Colorado", postal_code:"80202", brewery_type:"micro", phone:"3031110003", website_url:"http://ironhillbrew.com" },
{ name:"Golden Grain Brewery", street:"45 Market St", city:"San Diego", state:"California", postal_code:"92101", brewery_type:"micro", phone:"6191110004", website_url:"http://goldengrainbrew.com" },
{ name:"Hawk Ridge Brewing", street:"301 Cedar St", city:"Boise", state:"Idaho", postal_code:"83702", brewery_type:"brewpub", phone:"2081110005", website_url:"http://hawkridgebrew.com" },
{ name:"Wild Trail Brewery", street:"77 Forest Ave", city:"Eugene", state:"Oregon", postal_code:"97401", brewery_type:"micro", phone:"5411110006", website_url:"http://wildtrailbrew.com" },
{ name:"Copper Tank Brewery", street:"620 4th St", city:"Austin", state:"Texas", postal_code:"78701", brewery_type:"micro", phone:"5121110007", website_url:"http://coppertankbrew.com" },
{ name:"Pioneer Craft Brewing", street:"88 Pioneer Way", city:"Salem", state:"Oregon", postal_code:"97301", brewery_type:"micro", phone:"5031110008", website_url:"http://pioneerbrew.com" },
{ name:"Twin Peaks Brewery", street:"500 Hilltop Rd", city:"Boulder", state:"Colorado", postal_code:"80301", brewery_type:"micro", phone:"3031110009", website_url:"http://twinpeaksbrew.com" },
{ name:"Silver Lake Brewing", street:"990 Lake Dr", city:"Minneapolis", state:"Minnesota", postal_code:"55401", brewery_type:"micro", phone:"6121110010", website_url:"http://silverlbrew.com" },

{ name:"Sunset Barrel Brewery", street:"10 Ocean Ave", city:"Santa Cruz", state:"California", postal_code:"95060", brewery_type:"brewpub", phone:"8311110011", website_url:"http://sunsetbarrel.com" },
{ name:"North Harbor Brewing", street:"72 Dock St", city:"Seattle", state:"Washington", postal_code:"98101", brewery_type:"micro", phone:"2061110012", website_url:"http://northharborbrew.com" },
{ name:"Great Valley Brewing", street:"100 Valley Rd", city:"Phoenix", state:"Arizona", postal_code:"85001", brewery_type:"micro", phone:"6021110013", website_url:"http://greatvalleybrew.com" },
{ name:"Red Canyon Brewing", street:"540 Canyon Dr", city:"Moab", state:"Utah", postal_code:"84532", brewery_type:"micro", phone:"4351110014", website_url:"http://redcanyonbrew.com" },
{ name:"Blue Harbor Brewery", street:"44 Bay St", city:"San Francisco", state:"California", postal_code:"94102", brewery_type:"micro", phone:"4151110015", website_url:"http://blueharborbrew.com" },
{ name:"Stone Gate Brewery", street:"600 Gate Ave", city:"Sacramento", state:"California", postal_code:"95814", brewery_type:"micro", phone:"9161110016", website_url:"http://stonegatebrew.com" },
{ name:"Golden Hop Brewing", street:"12 Hop Ln", city:"Yakima", state:"Washington", postal_code:"98901", brewery_type:"micro", phone:"5091110017", website_url:"http://goldenhopbrew.com" },
{ name:"Mountain Pass Brewery", street:"740 Pass Rd", city:"Flagstaff", state:"Arizona", postal_code:"86001", brewery_type:"micro", phone:"9281110018", website_url:"http://mountainpassbrew.com" },
{ name:"Timber Creek Brewing", street:"111 Creek Dr", city:"Spokane", state:"Washington", postal_code:"99201", brewery_type:"micro", phone:"5091110019", website_url:"http://timbercreekbrew.com" },
{ name:"Old Mill Brewing", street:"700 Mill St", city:"Madison", state:"Wisconsin", postal_code:"53703", brewery_type:"brewpub", phone:"6081110020", website_url:"http://oldmillbrew.com" },

{ name:"River Stone Brewery", street:"88 River St", city:"Kansas City", state:"Missouri", postal_code:"64101", brewery_type:"micro", phone:"8161110021", website_url:"http://riverstonebrew.com" },
{ name:"Iron Forge Brewing", street:"33 Forge Rd", city:"Pittsburgh", state:"Pennsylvania", postal_code:"15201", brewery_type:"micro", phone:"4121110022", website_url:"http://ironforgebrew.com" },
{ name:"Harbor Light Brewing", street:"9 Harbor St", city:"Boston", state:"Massachusetts", postal_code:"02108", brewery_type:"micro", phone:"6171110023", website_url:"http://harborlightbrew.com" },
{ name:"Northern Sky Brewing", street:"500 Aurora Ave", city:"Anchorage", state:"Alaska", postal_code:"99501", brewery_type:"micro", phone:"9071110024", website_url:"http://northernskybrew.com" },
{ name:"Prairie Wind Brewing", street:"200 Plains Rd", city:"Omaha", state:"Nebraska", postal_code:"68102", brewery_type:"micro", phone:"4021110025", website_url:"http://prairiewindbrew.com" },

{ name:"Copper Trail Brewery", street:"90 Trail Rd", city:"Cheyenne", state:"Wyoming", postal_code:"82001", brewery_type:"micro", phone:"3071110026", website_url:"http://coppertrailbrew.com" },
{ name:"Black Bear Brewing", street:"77 Pine St", city:"Bozeman", state:"Montana", postal_code:"59715", brewery_type:"micro", phone:"4061110027", website_url:"http://blackbearbrew.com" },
{ name:"Blue Ridge Brewing", street:"900 Ridge Rd", city:"Asheville", state:"North Carolina", postal_code:"28801", brewery_type:"micro", phone:"8281110028", website_url:"http://blueridgebrew.com" },
{ name:"Sun Valley Brewing", street:"150 Sun Dr", city:"Idaho Falls", state:"Idaho", postal_code:"83401", brewery_type:"micro", phone:"2081110029", website_url:"http://sunvalleybrew.com" },
{ name:"Silver Peak Brewing", street:"600 Peak St", city:"Reno", state:"Nevada", postal_code:"89501", brewery_type:"micro", phone:"7751110030", website_url:"http://silverpeakbrew.com" },

{ name:"Crystal Lake Brewing", street:"88 Crystal Dr", city:"Orlando", state:"Florida", postal_code:"32801", brewery_type:"micro", phone:"4071110031", website_url:"http://crystallakebrew.com" },
{ name:"Bayfront Brewing", street:"100 Bay St", city:"Tampa", state:"Florida", postal_code:"33602", brewery_type:"micro", phone:"8131110032", website_url:"http://bayfrontbrew.com" },
{ name:"Lone Star Brewing Co", street:"200 Ranch Rd", city:"Dallas", state:"Texas", postal_code:"75201", brewery_type:"micro", phone:"2141110033", website_url:"http://lonestarbrewco.com" },
{ name:"Red River Brewing", street:"400 River Rd", city:"Shreveport", state:"Louisiana", postal_code:"71101", brewery_type:"micro", phone:"3181110034", website_url:"http://redriverbrew.com" },
{ name:"Bayou Barrel Brewing", street:"10 Bayou Rd", city:"Baton Rouge", state:"Louisiana", postal_code:"70801", brewery_type:"micro", phone:"2251110035", website_url:"http://bayoubarrelbrew.com" },

{ name:"Great Plains Brewing", street:"700 Prairie Rd", city:"Wichita", state:"Kansas", postal_code:"67202", brewery_type:"micro", phone:"3161110036", website_url:"http://greatplainsbrew.com" },
{ name:"Capitol Craft Brewery", street:"99 Capitol St", city:"Washington", state:"DC", postal_code:"20001", brewery_type:"brewpub", phone:"2021110037", website_url:"http://capitolcraftbrew.com" },
{ name:"Liberty Ale Brewery", street:"1776 Freedom Rd", city:"Philadelphia", state:"Pennsylvania", postal_code:"19106", brewery_type:"micro", phone:"2151110038", website_url:"http://libertyalebrew.com" },
{ name:"Empire State Brewing", street:"500 Madison Ave", city:"New York", state:"New York", postal_code:"10001", brewery_type:"micro", phone:"2121110039", website_url:"http://empirestatebrew.com" },
{ name:"Hudson River Brewing", street:"120 Hudson St", city:"Albany", state:"New York", postal_code:"12207", brewery_type:"micro", phone:"5181110040", website_url:"http://hudsonriverbrew.com" },

{ name:"Great Lakes Brewing House", street:"250 Lake Ave", city:"Cleveland", state:"Ohio", postal_code:"44101", brewery_type:"micro", phone:"2161110041", website_url:"http://greatlakesbrew.com" },
{ name:"Motor City Brewing", street:"333 Auto Dr", city:"Detroit", state:"Michigan", postal_code:"48201", brewery_type:"micro", phone:"3131110042", website_url:"http://motorcitybrew.com" },
{ name:"Windy City Brewing", street:"400 Lake Shore Dr", city:"Chicago", state:"Illinois", postal_code:"60601", brewery_type:"micro", phone:"3121110043", website_url:"http://windycitybrew.com" },
{ name:"Rocky Ridge Brewing", street:"888 Ridge Rd", city:"Colorado Springs", state:"Colorado", postal_code:"80903", brewery_type:"micro", phone:"7191110044", website_url:"http://rockyridgebrew.com" },
{ name:"Desert Sun Brewing", street:"222 Desert Rd", city:"Las Vegas", state:"Nevada", postal_code:"89101", brewery_type:"micro", phone:"7021110045", website_url:"http://desertsunbrew.com" },

{ name:"Pacific Tide Brewing", street:"55 Ocean Dr", city:"San Jose", state:"California", postal_code:"95112", brewery_type:"micro", phone:"4081110046", website_url:"http://pacifictidebrew.com" },
{ name:"Cascade Falls Brewery", street:"999 Waterfall Rd", city:"Tacoma", state:"Washington", postal_code:"98402", brewery_type:"micro", phone:"2531110047", website_url:"http://cascadefallsbrew.com" },
{ name:"Redwood Trail Brewing", street:"11 Redwood Ln", city:"Santa Rosa", state:"California", postal_code:"95401", brewery_type:"micro", phone:"7071110048", website_url:"http://redwoodtrailbrew.com" },
{ name:"Granite Peak Brewing", street:"600 Granite Rd", city:"St Paul", state:"Minnesota", postal_code:"55101", brewery_type:"micro", phone:"6511110049", website_url:"http://granitepeakbrew.com" },
{ name:"Northern Trail Brewing", street:"120 North Rd", city:"Duluth", state:"Minnesota", postal_code:"55802", brewery_type:"micro", phone:"2181110050", website_url:"http://northerntrailbrew.com" }
]
